In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
print("Labraries imported successfully!")

Labraries imported successfully!

In [ ]:
url="https://books.toscrape.com/"
response=requests.get(url)
print("Status Code:",response.status_code)

Status Code: 200

In [ ]:
soup=BeautifulSoup(response.text,"html.parser")
print(soup.title.text)

    All products | Books to Scrape - Sandbox

In [ ]:
books=soup.find_all("article",class_="product_pod")
print("Number of books found:",len(books))

Number of books found: 20

In [ ]:
first_book=books[0]

title=first_book.h3.a["title"]
price=first_book.find("p",class_="price_color").text.strip()
rating=first_book.find("p",class_="star-rating")["class"][1]
availability=first_book.find("p",class_="instock").text.strip()


print("Title:",title)
print("Price:",price)
print("Rating:",rating)
print("Availability:",availability)

Title: A Light in the Attic
Price: Â£51.77
Rating: Three
Availability: In stock

In [ ]:
books_data=[]

for book in books:
  title=book.h3.a["title"]
  price=book.find("p",class_="price_color").text.strip()
  rating=book.find("p",class_="star-rating")["class"][1]
  availability=book.find("p",class_="instock").text.strip()

  books_data.append({
      "Title":title,
      "Price":price,
      "Rating":rating,
      "Availability":availability
  })

  print("Books extracted:",len(books_data))

Books extracted: 1
Books extracted: 2
Books extracted: 3
Books extracted: 4
Books extracted: 5
Books extracted: 6
Books extracted: 7
Books extracted: 8
Books extracted: 9
Books extracted: 10
Books extracted: 11
Books extracted: 12
Books extracted: 13
Books extracted: 14
Books extracted: 15
Books extracted: 16
Books extracted: 17
Books extracted: 18
Books extracted: 19
Books extracted: 20

In [ ]:
df=pd.DataFrame(books_data)
print("Dataset created successfully!")
print("Dataset shape:",df.shape)
df.head()

Dataset created successfully!
Dataset shape: (20, 4)

                                   Title    Price Rating Availability
0                   A Light in the Attic  Â£51.77  Three     In stock
1                     Tipping the Velvet  Â£53.74    One     In stock
2                             Soumission  Â£50.10    One     In stock
3                          Sharp Objects  Â£47.82   Four     In stock
4  Sapiens: A Brief History of Humankind  Â£54.23   Five     In stock

In [ ]:
from urllib.parse import urljoin

books_data=[]

for book in books:
  title=book.h3.a["title"]
  price=book.find("p",class_="price_color").text.strip()
  rating=book.find("p",class_="star-rating")["class"][1]
  availability=book.find("p",class_="instock").text.strip()

  product_url=urljoin(url,book.h3.a["href"])

books_data.append({
     "Title":title,
      "Price":price,
      "Rating":rating,
      "Availability":availability,
      "Product URL":product_url
})

df=pd.DataFrame(books_data)

print(" Final Dataset shape:",df.shape)

df.head()

 Final Dataset shape: (1, 5)

,Title,Price,Rating,Availability,Product URL
0,It's Only the Himalayas,Â£45.17,Two,In stock,https://books.toscrape.com/catalogue/its-only-...

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from urllib.parse import urljoin

url="https://books.toscrape.com"

response=requests.get(url,headers={"User-Agent":"Mozilla/5.0"},timeout=15)
print("Status code:",response.status_code)

soup= BeautifulSoup(response.text,"html.parser")
all_books=soup.select("article.product_pod")
print("Books found:",len(all_books))

data=[]

for book in all_books:

  title=book.select_one("h3 a")["title"]

  price=book.select_one("p.price_color").get_text(strip=True)

  rating=book.select_one("p.star-rating")["class"][1]

  availability = book.select_one("p.instock.availability").get_text(" ",strip=True)

  product_url = urljoin(url,book.select_one("h3 a")["href"]
  )
  data.append([
      title,
      price,
      rating,
      availability,
      product_url
  ])
  df=pd.DataFrame(data,columns=[
      "Title",
      "Price" ,
      "Rating",
      "Availability",
      "Product_url "
      ])
  print("\n+=========================================")
  print("FINAL DATASET")
  print("\n+=========================================")
  print("Books collected:",len(df))
  print("Dataset sahpe:",df.shape)

  df.head()

Status code: 200
Books found: 20

+=========================================
FINAL DATASET

+=========================================
Books collected: 1
Dataset sahpe: (1, 5)

+=========================================
FINAL DATASET

+=========================================
Books collected: 2
Dataset sahpe: (2, 5)

+=========================================
FINAL DATASET

+=========================================
Books collected: 3
Dataset sahpe: (3, 5)

+=========================================
FINAL DATASET

+=========================================
Books collected: 4
Dataset sahpe: (4, 5)

+=========================================
FINAL DATASET

+=========================================
Books collected: 5
Dataset sahpe: (5, 5)

+=========================================
FINAL DATASET

+=========================================
Books collected: 6
Dataset sahpe: (6, 5)

+=========================================
FINAL DATASET

+=========================================
Books collected: 7
Dataset sahpe: (7, 5)

+=========================================
FINAL DATASET

+=========================================
Books collected: 8
Dataset sahpe: (8, 5)

+=========================================
FINAL DATASET

+=========================================
Books collected: 9
Dataset sahpe: (9, 5)

+=========================================
FINAL DATASET

+=========================================
Books collected: 10
Dataset sahpe: (10, 5)

+=========================================
FINAL DATASET

+=========================================
Books collected: 11
Dataset sahpe: (11, 5)

+=========================================
FINAL DATASET

+=========================================
Books collected: 12
Dataset sahpe: (12, 5)

+=========================================
FINAL DATASET

+=========================================
Books collected: 13
Dataset sahpe: (13, 5)

+=========================================
FINAL DATASET

+=========================================
Books collected: 14
Dataset sahpe: (14, 5)

+=========================================
FINAL DATASET

+=========================================
Books collected: 15
Dataset sahpe: (15, 5)

+=========================================
FINAL DATASET

+=========================================
Books collected: 16
Dataset sahpe: (16, 5)

+=========================================
FINAL DATASET

+=========================================
Books collected: 17
Dataset sahpe: (17, 5)

+=========================================
FINAL DATASET

+=========================================
Books collected: 18
Dataset sahpe: (18, 5)

+=========================================
FINAL DATASET

+=========================================
Books collected: 19
Dataset sahpe: (19, 5)

+=========================================
FINAL DATASET

+=========================================
Books collected: 20
Dataset sahpe: (20, 5)

In [ ]:
print("====FINAL DATASET CHECK====")
print("Shape:",df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nMissing Values:")
print(df.duplicated().sum())

print("\nDuplicate Rows:")
print(df.isnull().sum())

print("\nFirst 5 Records:")
display(df.head())

====FINAL DATASET CHECK====
Shape: (20, 5)

Columns:
['Title', 'Price', 'Rating', 'Availability', 'Product_url ']

Missing Values:
0

Duplicate Rows:
Title           0
Price           0
Rating          0
Availability    0
Product_url     0
dtype: int64

First 5 Records:

,Title,Price,Rating,Availability,Product_url
0,A Light in the Attic,Â£51.77,Three,In stock,https://books.toscrape.com/catalogue/a-light-i...
1,Tipping the Velvet,Â£53.74,One,In stock,https://books.toscrape.com/catalogue/tipping-t...
2,Soumission,Â£50.10,One,In stock,https://books.toscrape.com/catalogue/soumissio...
3,Sharp Objects,Â£47.82,Four,In stock,https://books.toscrape.com/catalogue/sharp-obj...
4,Sapiens: A Brief History of Humankind,Â£54.23,Five,In stock,https://books.toscrape.com/catalogue/sapiens-a...

In [ ]:
df.to_csv("books_data.csv",index=False)
print("books_data.csv created successfully!")

books_data.csv created successfully!

In [ ]:
from google.colab import files
files.download("books_data.csv")

In [ ]:
print("====FINAL SCRAPED DATASET====")

print("Total Records:",len(df))
print("Total Columns:",len(df.columns))
display(df)

====FINAL SCRAPED DATASET====
Total Records: 20
Total Columns: 5

,Title,Price,Rating,Availability,Product_url
0,A Light in the Attic,Â£51.77,Three,In stock,https://books.toscrape.com/catalogue/a-light-i...
1,Tipping the Velvet,Â£53.74,One,In stock,https://books.toscrape.com/catalogue/tipping-t...
2,Soumission,Â£50.10,One,In stock,https://books.toscrape.com/catalogue/soumissio...
3,Sharp Objects,Â£47.82,Four,In stock,https://books.toscrape.com/catalogue/sharp-obj...
4,Sapiens: A Brief History of Humankind,Â£54.23,Five,In stock,https://books.toscrape.com/catalogue/sapiens-a...
5,The Requiem Red,Â£22.65,One,In stock,https://books.toscrape.com/catalogue/the-requi...
6,The Dirty Little Secrets of Getting Your Dream...,Â£33.34,Four,In stock,https://books.toscrape.com/catalogue/the-dirty...
7,The Coming Woman: A Novel Based on the Life of...,Â£17.93,Three,In stock,https://books.toscrape.com/catalogue/the-comin...
8,The Boys in the Boat: Nine Americans and Their...,Â£22.60,Four,In stock,https://books.toscrape.com/catalogue/the-boys-...
9,The Black Maria,Â£52.15,One,In stock,https://books.toscrape.com/catalogue/the-black...
10,"Starving Hearts (Triangular Trade Trilogy, #1)",Â£13.99,Two,In stock,https://books.toscrape.com/catalogue/starving-...
11,Shakespeare's Sonnets,Â£20.66,Four,In stock,https://books.toscrape.com/catalogue/shakespea...
12,Set Me Free,Â£17.46,Five,In stock,https://books.toscrape.com/catalogue/set-me-fr...
13,Scott Pilgrim's Precious Little Life (Scott Pi...,Â£52.29,Five,In stock,https://books.toscrape.com/catalogue/scott-pil...
14,Rip it Up and Start Again,Â£35.02,Five,In stock,https://books.toscrape.com/catalogue/rip-it-up...
15,Our Band Could Be Your Life: Scenes from the A...,Â£57.25,Three,In stock,https://books.toscrape.com/catalogue/our-band-...
16,Olio,Â£23.88,One,In stock,https://books.toscrape.com/catalogue/olio_984/...
17,Mesaerion: The Best Science Fiction Stories 18...,Â£37.59,One,In stock,https://books.toscrape.com/catalogue/mesaerion...
18,Libertarianism for Beginners,Â£51.33,Two,In stock,https://books.toscrape.com/catalogue/libertari...
19,It's Only the Himalayas,Â£45.17,Two,In stock,https://books.toscrape.com/catalogue/its-only-...